[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = false
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'qstest-1'
rpc_addr = 'http://quicksilver:26657'
grpc_addr = 'http://quicksilver:9090'
websocket_addr = 'ws://quicksilver:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'quick'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 5000000
gas_price = { price = 0.000000, denom = 'uqck' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '3minutes'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
id = 'lstest-1'
rpc_addr = 'http://testzone1-1:26657'
grpc_addr = 'http://testzone1-1:9090'
websocket_addr = 'ws://testzone1-1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uqck' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '3minutes'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

#[[chains]]
#id = 'lstest-2'
#rpc_addr = 'http://testzone2-1:26657'
#grpc_addr = 'http://testzone2-1:9090'
#websocket_addr = 'ws://testzone2-1:26657/websocket'
#rpc_timeout = '10s'
#account_prefix = 'osmo'
#key_name = 'testkey'
#store_prefix = 'ibc'
#default_gas = 100000
#max_gas = 3000000
#gas_price = { price = 0.000, denom = 'uosmo' }
#gas_multiplier = 1.5
#max_msg_num = 30
#max_tx_size = 2097152
#clock_drift = '5s'
#max_block_time = '10s'
#trusting_period = '14days'
#trust_threshold = { numerator = '1', denominator = '3' }
#address_type = { derivation = 'cosmos' }
