default_chain: qstest-1
chains:
  qstest-1:
    key: test
    chain-id: qstest-1
    rpc-addr: http://quicksilver:26657
    grpc-addr: http://quicksilver:9090
    account-prefix: quick
    keyring-backend: test
    gas-adjustment: 1.5
    gas-prices: 0.00uqck
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    output-format: json
    sign-mode: direct
  lstest-1:
    key: test
    chain-id: lstest-1
    rpc-addr: http://testzone1-1:26657
    grpc-addr: http://testzone1-1:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.5
    gas-prices: 0.00uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    output-format: json
    sign-mode: direct
  lstest-2:
    key: test
    chain-id: lstest-2
    rpc-addr: http://testzone2-1:26657
    grpc-addr: http://testzone2-1:9090
    account-prefix: osmo
    keyring-backend: test
    gas-adjustment: 1.5
    gas-prices: 0.00uosmo
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    output-format: json
    sign-mode: direct
