name: Web UI Dev Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]
    paths:
    - web-ui/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - web-ui/**

jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@^33.2.0 # Replace with the current major version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # or specify a version

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: quicksilver
          ALIAS_DOMAINS: |
            {BRANCH}.app-dev.quicksilver.zone
          PR_PREVIEW_DOMAIN: "pr-{PR}.app-dev.quicksilver.zone"

