name: Build & Deploy web-ui with dev environment to Github Pages

on:
  push:
    branches:
      - bunDev
    paths:
      - web-ui/**
  pull_request:
    branches:
      - bunDev2
    paths:
      - web-ui/**

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  deployments: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Environment File
        run: |
          cd web-ui
          cp .env.development .env

      - name: Install Dependencies
        run: |
          cd web-ui
          bun install

      - name: Build Project
        run: |
          cd web-ui
          bun run build

      - name: Export Project
        run: |
          cd web-ui
          bun export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-ui/out
